esphome:
  name: wolfdungeon_thermostat
  on_boot:
    priority: 500
    then:
      - lambda: |-
          id(wolfdungeon_thermostat).target_temperature = id(last_known_target_temperature);
          id(boot_complete) = true;

esp8266:
  board: nodemcuv2
  restore_from_flash: true

preferences:
  flash_write_interval: 5min

wifi:
  ssid: !secret ssid  
  password: !secret wappw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dungeon Climate Fallback Hotspot"
    password: !secret hotspotpw

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret apipw

ota:
  password: !secret apipw

### PIN MAPPINGS ###

# D0      - Unused
# D1      - Thermosensor
# D2      - Display Enable
# D3(OUT) - Display Data
# D4(OUT) - Display Clock
# D5      - Encoder Switch
# D6      - Encoder Clock
# D7      - Encoder Signal
# D8(OUT) - Heater Relay

### BEGIN GOOD STUFF ###

globals:
    # We need to suppress calls to display.update() until the display has
    # been fully set up, or we'll get segfaults
  - id: boot_complete
    type: bool
    restore_value: false
    initial_value: 'false'
  - id: system_on
    type: bool
    restore_value: true
    initial_value: 'false'
  - id: display_enabled
    type: bool
    restore_value: true
    initial_value: 'true'
  - id: last_known_target_temperature
    type: float
    restore_value: true
    initial_value: '23.33'

# MAX7219 Configuration
spi:
  clk_pin: D4
  mosi_pin: D3

display:
  - platform: max7219
    id: temp_display
    cs_pin: D2
    num_chips: 1
    reverse_enable: true
    lambda: |-
      if (id(display_enabled)) {
        it.printf(0, "%2.0f", id(wolfdungeon_thermostat).current_temperature * (9.0/5.0) + 32.0);  // Bottom Blue Display
        if (id(system_on)) {
          if (id(heater).state) {
            it.printf(6, "%2.0f", id(wolfdungeon_thermostat).target_temperature * (9.0/5.0) + 32.0); // Top Red Display
          } else {
            it.printf(6, "%2.0f", id(wolfdungeon_thermostat).target_temperature * (9.0/5.0) + 32.0); // Top Red Display
            it.printf(2, "%2.0f", id(wolfdungeon_thermostat).target_temperature * (9.0/5.0) + 32.0); // Top Blue Display
            it.printf(4, "%2.0f", id(wolfdungeon_thermostat).target_temperature * (9.0/5.0) + 32.0); // Top Green Display
          }
        }
      }

sensor:
  - platform: dht
    model: DHT22
    pin: D1
    temperature:
      name: "Wolf Dungeon Thermostat Temperature"
      id: wolfdungeon_sensor
      unit_of_measurement: "°C"
      filters:
       - calibrate_polynomial:
          degree: 2
          datapoints:
            - 21.89 -> 19.78
            - 23.61 -> 20.72
            - 25.61 -> 22.22
            - 27.89 -> 22.11
            - 28.28 -> 23.11
    humidity:
      name: "Wolf Dungeon Thermostat Humidity"
    update_interval: 10s
  - platform: wifi_signal
    name: "Wolf Dungeon Thermostat Wifi"
    update_interval: 60s
  - platform: rotary_encoder
    id: rot_enc
    internal: true
    # min_value: 10
    # max_value: 37
    on_clockwise:
      - script.execute: display_sleep_timer
      - lambda: |-
          if ((id(wolfdungeon_thermostat).mode == CLIMATE_MODE_HEAT) && (id(wolfdungeon_thermostat).target_temperature < 32.22)) {
            id(wolfdungeon_thermostat).target_temperature += 0.555;
            id(temp_display).update();
          }
      - script.execute: set_point_timer
    on_anticlockwise:
      - script.execute: display_sleep_timer
      - lambda: |-
          if ((id(wolfdungeon_thermostat).mode == CLIMATE_MODE_HEAT) && (id(wolfdungeon_thermostat).target_temperature > 10.0)) {
            id(wolfdungeon_thermostat).target_temperature -= 0.555;
            id(temp_display).update();
          }
      - script.execute: set_point_timer
    pin_a:
      number: D6
      mode: INPUT_PULLUP
    pin_b: 
      number: D7
      mode: INPUT_PULLUP
  - platform: template
    name: "Wolf Dungeon Heater Power"
    id: wolf_dungeon_heater_power
    unit_of_measurement: kW
    lambda: |-
      if (id(heater).state) {
        return 0.5; // 2.1A, 500W for 120V heater
      } else {
        return 0.0;
      }     
  - platform: total_daily_energy
    name: "Wolf Dungeon Heater Consumption"
    power_id: wolf_dungeon_heater_power

binary_sensor:
  - platform: gpio
    id: rot_sw
    pin: 
      number: D5
      mode: INPUT_PULLUP
    internal: true
    filters:
      - invert: 
    on_click:
      - script.execute: display_sleep_timer
      - lambda: |-
          auto call = id(wolfdungeon_thermostat).make_call();
          if (id(wolfdungeon_thermostat).mode == CLIMATE_MODE_HEAT) {
            call.set_mode("OFF");
          } else {
            call.set_mode("HEAT");
          }
          call.perform();

output:
  - platform: template
    id: display_timer_enabled
    type: binary
    write_action:
      - script.execute: display_sleep_timer

switch:
  - platform: gpio
    pin: D8
    internal: true
    id: heater
  - platform: output
    name: "Wolf Dungeon Thermostat Display Timer"
    id: display_timer_switch
    output: display_timer_enabled

script:
  - id: set_point_timer
    mode: restart
    then: 
      - delay: 2s
      # climate component doesn't support update(), so we submit an empty api call to update the frontend
      - lambda: |-
          auto call = id(wolfdungeon_thermostat).make_call();
          call.perform();
  - id: display_sleep_timer
    mode: restart
    then: 
      - lambda: |-
          id(display_enabled) = true;
          if (id(boot_complete)) {
            id(temp_display).update();
          }
      - delay: 5s
      - lambda: |-
          if (id(display_timer_switch).state) {
            id(display_enabled) = false;
            if (id(boot_complete)) {
              id(temp_display).update();
            }
          }

climate:
  - platform: thermostat
    name: Wolf Dungeon Thermostat
    id: wolfdungeon_thermostat
    sensor: wolfdungeon_sensor
    min_idle_time: 10s
    min_heating_off_time: 10s
    min_heating_run_time: 10s
    preset:
      - name: Home
        default_target_temperature_low: 23.33
    visual:
      min_temperature: 10
      max_temperature: 32.22
      temperature_step: 1.0
    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: heater
    heat_mode:
      - lambda: 'id(system_on) = true;'
    off_mode:
      - lambda: 'id(system_on) = false;'
    target_temperature_change_action:
      - lambda: id(last_known_target_temperature) = id(wolfdungeon_thermostat).target_temperature;

# Required for integrating kWh
time:
  - platform: sntp